[package]
name = "aboutme"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.24"
serde = "1"
log = "0.4"
gloo = "0.8"
lipsum = "0.8.2"
once_cell = "1"
gloo-timers = "0.2"
strum_macros = "0.24"
serde_derive = "1"
instant = { version = "0.1", features = ["wasm-bindgen"] }
getrandom = { version = "0.2", features = ["js"] }
rand = { version = "0.8", features = ["small_rng"] }


[dependencies.yew-router]
version = "0.16"

[dependencies.yew]
version = "0.19"

[dependencies.web-sys]
version = "0.3"
features = [
	"HtmlInputElement",
]
