[build]
target = "index.html"
release = false
dist = "dist"
filehash = false

[serve]
address = "127.0.0.1"
port = 8080
open = false
no_autoreload = false

[watch]
watch = ["./src", "./static/tailwind.css", "./index.html"]
ignore = ["node_modules", ".git", "target"]

[[hooks]]
stage = "pre_build"
command = "npm"
command_arguments = ["run", "build"]
